/**
 * Exercises Seed Script
 *
 * Inserts the initial exercise catalog (33 exercises).
 * Idempotent: skips insertion if exercises already exist.
 * Run with: npm run seed:exercises
 *
 * Required env vars:
 *   MONGODB_URI — MongoDB connection string
 */

import mongoose from 'mongoose';
import * as dotenv from 'dotenv';
import * as path from 'path';
import { Exercise, ExerciseSchema } from '../../schemas/exercise.schema';

dotenv.config({
  path: path.resolve(process.cwd(), `.env.${process.env.NODE_ENV ?? 'local'}`),
});

const EXERCISES = [
  // ── Chest ──────────────────────────────────────────────────────────────
  {
    name: 'Barbell Bench Press',
    musclesPrimary: ['chest'],
    musclesSecondary: ['front_delts', 'triceps'],
    loadType: 'barbell',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Incline Dumbbell Press',
    musclesPrimary: ['chest', 'front_delts'],
    musclesSecondary: ['triceps'],
    loadType: 'dumbbell',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Push-Up',
    musclesPrimary: ['chest', 'triceps'],
    musclesSecondary: ['front_delts'],
    loadType: 'bodyweight',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Decline Dumbbell Fly',
    musclesPrimary: ['chest'],
    musclesSecondary: ['front_delts'],
    loadType: 'dumbbell',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'High Cable Fly',
    musclesPrimary: ['chest'],
    musclesSecondary: ['front_delts'],
    loadType: 'cable',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Low Cable Fly',
    musclesPrimary: ['chest'],
    musclesSecondary: ['front_delts'],
    loadType: 'cable',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Incline Dumbbell Fly',
    musclesPrimary: ['chest'],
    musclesSecondary: ['front_delts'],
    loadType: 'dumbbell',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Flat Dumbbell Fly',
    musclesPrimary: ['chest'],
    musclesSecondary: ['front_delts'],
    loadType: 'dumbbell',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Decline Barbell Bench Press',
    musclesPrimary: ['chest'],
    musclesSecondary: ['triceps', 'front_delts'],
    loadType: 'barbell',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Decline Dumbbell Bench Press',
    musclesPrimary: ['chest'],
    musclesSecondary: ['triceps', 'front_delts'],
    loadType: 'dumbbell',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Incline Barbell Bench Press',
    musclesPrimary: ['chest'],
    musclesSecondary: ['triceps', 'front_delts'],
    loadType: 'barbell',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Flat Dumbbell Bench Press',
    musclesPrimary: ['chest'],
    musclesSecondary: ['triceps', 'front_delts'],
    loadType: 'dumbbell',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Chest Press Machine',
    musclesPrimary: ['chest'],
    musclesSecondary: ['triceps', 'front_delts'],
    loadType: 'machine',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Pec Deck Machine',
    musclesPrimary: ['chest'],
    musclesSecondary: ['front_delts'],
    loadType: 'machine',
    trackingType: 'reps',
    bilateral: true,
  },

  // ── Back ───────────────────────────────────────────────────────────────
  {
    name: 'Pull-Up',
    musclesPrimary: ['lats', 'upper_back'],
    musclesSecondary: ['biceps'],
    loadType: 'bodyweight',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Face Pull',
    musclesPrimary: ['rear_delts', 'upper_back'],
    musclesSecondary: ['traps'],
    loadType: 'cable',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Kelso Shrug',
    musclesPrimary: ['upper_back', 'traps'],
    musclesSecondary: ['rear_delts'],
    loadType: 'barbell',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Neutral Grip Lat Pulldown',
    musclesPrimary: ['lats'],
    musclesSecondary: ['biceps', 'upper_back'],
    loadType: 'cable',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Close Grip Lat Pulldown',
    musclesPrimary: ['lats'],
    musclesSecondary: ['biceps', 'upper_back'],
    loadType: 'cable',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Pronated Grip Lat Pulldown',
    musclesPrimary: ['lats'],
    musclesSecondary: ['biceps', 'upper_back'],
    loadType: 'cable',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Barbell Row',
    musclesPrimary: ['lats', 'upper_back'],
    musclesSecondary: ['biceps', 'lower_back', 'rear_delts'],
    loadType: 'barbell',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'One-Arm Dumbbell Row',
    musclesPrimary: ['lats'],
    musclesSecondary: ['upper_back', 'biceps', 'rear_delts'],
    loadType: 'dumbbell',
    trackingType: 'reps',
    bilateral: false,
  },
  {
    name: 'Machine Row Neutral Grip',
    musclesPrimary: ['lats', 'upper_back'],
    musclesSecondary: ['biceps', 'rear_delts'],
    loadType: 'machine',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Machine Row Supinated Grip',
    musclesPrimary: ['lats'],
    musclesSecondary: ['biceps', 'upper_back'],
    loadType: 'machine',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Machine Row Pronated Grip',
    musclesPrimary: ['upper_back'],
    musclesSecondary: ['lats', 'rear_delts', 'biceps'],
    loadType: 'machine',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'T-Bar Row',
    musclesPrimary: ['lats', 'upper_back'],
    musclesSecondary: ['biceps', 'rear_delts', 'lower_back'],
    loadType: 'barbell',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Wide Grip Seated Cable Row',
    musclesPrimary: ['upper_back'],
    musclesSecondary: ['lats', 'rear_delts', 'biceps'],
    loadType: 'cable',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Close Grip Seated Cable Row',
    musclesPrimary: ['lats'],
    musclesSecondary: ['upper_back', 'biceps'],
    loadType: 'cable',
    trackingType: 'reps',
    bilateral: true,
  },

  // ── Shoulders  ─────────────────────────────────────────────────────────
  {
    name: 'Dumbbell Lateral Raise',
    musclesPrimary: ['side_delts'],
    musclesSecondary: [],
    loadType: 'dumbbell',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Single-Arm Cable Rear Delt Fly',
    musclesPrimary: ['rear_delts'],
    musclesSecondary: ['upper_back'],
    loadType: 'cable',
    trackingType: 'reps',
    bilateral: false,
  },
  {
    name: 'Incline Dumbbell Rear Delt Fly',
    musclesPrimary: ['rear_delts'],
    musclesSecondary: ['upper_back'],
    loadType: 'dumbbell',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Pec Deck Rear Delt Fly',
    musclesPrimary: ['rear_delts'],
    musclesSecondary: ['upper_back'],
    loadType: 'machine',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Front Raise (Dumbbell)',
    musclesPrimary: ['front_delts'],
    musclesSecondary: ['side_delts'],
    loadType: 'dumbbell',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Dumbbell Lateral Raise',
    musclesPrimary: ['side_delts'],
    musclesSecondary: ['front_delts', 'traps'],
    loadType: 'dumbbell',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Machine Lateral Raise',
    musclesPrimary: ['side_delts'],
    musclesSecondary: ['traps'],
    loadType: 'machine',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Cable Lateral Raise (Bilateral)',
    musclesPrimary: ['side_delts'],
    musclesSecondary: ['traps'],
    loadType: 'cable',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Single-Arm Cable Lateral Raise',
    musclesPrimary: ['side_delts'],
    musclesSecondary: ['traps'],
    loadType: 'cable',
    trackingType: 'reps',
    bilateral: false,
  },
  {
    name: 'Single Dumbbell Front Raise',
    musclesPrimary: ['front_delts'],
    musclesSecondary: ['side_delts'],
    loadType: 'dumbbell',
    trackingType: 'reps',
    bilateral: false,
  },
  {
    name: 'Seated Arnold Press',
    musclesPrimary: ['front_delts', 'side_delts'],
    musclesSecondary: ['triceps'],
    loadType: 'dumbbell',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Machine Shoulder Press',
    musclesPrimary: ['front_delts', 'side_delts'],
    musclesSecondary: ['triceps'],
    loadType: 'machine',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Seated Dumbbell Shoulder Press',
    musclesPrimary: ['front_delts', 'side_delts'],
    musclesSecondary: ['triceps'],
    loadType: 'dumbbell',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Standing Military Press',
    musclesPrimary: ['front_delts', 'side_delts'],
    musclesSecondary: ['triceps', 'abs', 'lower_back'],
    loadType: 'barbell',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Cable External Shoulder Rotation',
    musclesPrimary: ['rear_delts'],
    musclesSecondary: ['upper_back'],
    loadType: 'cable',
    trackingType: 'reps',
    bilateral: false,
  },
  {
    name: 'Cable Internal Shoulder Rotation',
    musclesPrimary: ['front_delts'],
    musclesSecondary: ['chest'],
    loadType: 'cable',
    trackingType: 'reps',
    bilateral: false,
  },

  // ── Biceps ──────────────────────────────────────────────────────────────
  {
    name: 'Barbell Bicep Curl',
    musclesPrimary: ['biceps'],
    musclesSecondary: ['forearms'],
    loadType: 'barbell',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Hammer Curl',
    musclesPrimary: ['biceps', 'forearms'],
    musclesSecondary: [],
    loadType: 'dumbbell',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Preacher Curl (Machine)',
    musclesPrimary: ['biceps'],
    musclesSecondary: [],
    loadType: 'machine',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Supinated Dumbbell Spider Curl',
    musclesPrimary: ['biceps'],
    musclesSecondary: ['forearms'],
    loadType: 'dumbbell',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Pronated Dumbbell Spider Curl',
    musclesPrimary: ['forearms'],
    musclesSecondary: ['biceps'],
    loadType: 'dumbbell',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Bayesian Cable Curl (Bilateral)',
    musclesPrimary: ['biceps'],
    musclesSecondary: ['forearms'],
    loadType: 'cable',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Bayesian Cable Curl (Single-Arm)',
    musclesPrimary: ['biceps'],
    musclesSecondary: ['forearms'],
    loadType: 'cable',
    trackingType: 'reps',
    bilateral: false,
  },
  {
    name: 'Concentration Curl',
    musclesPrimary: ['biceps'],
    musclesSecondary: ['forearms'],
    loadType: 'dumbbell',
    trackingType: 'reps',
    bilateral: false,
  },
  {
    name: 'Cable Biceps Curl',
    musclesPrimary: ['biceps'],
    musclesSecondary: ['forearms'],
    loadType: 'cable',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Barbell Biceps Curl',
    musclesPrimary: ['biceps'],
    musclesSecondary: ['forearms'],
    loadType: 'barbell',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Alternating Dumbbell Curl',
    musclesPrimary: ['biceps'],
    musclesSecondary: ['forearms'],
    loadType: 'dumbbell',
    trackingType: 'reps',
    bilateral: false,
  },
  {
    name: 'Dumbbell Curl with Rotation',
    musclesPrimary: ['biceps'],
    musclesSecondary: ['forearms'],
    loadType: 'dumbbell',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Pronated Dumbbell Curl',
    musclesPrimary: ['forearms'],
    musclesSecondary: ['biceps'],
    loadType: 'dumbbell',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Incline Dumbbell Curl',
    musclesPrimary: ['biceps'],
    musclesSecondary: ['forearms'],
    loadType: 'dumbbell',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Cable Hammer Curl',
    musclesPrimary: ['biceps'],
    musclesSecondary: ['forearms'],
    loadType: 'cable',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Curl Scott Machine',
    musclesPrimary: ['biceps'],
    musclesSecondary: ['forearms'],
    loadType: 'machine',
    trackingType: 'reps',
    bilateral: true,
  },

  // ── Triceps ──────────────────────────────────────────────────────────────
  {
    name: 'Skull Crushers',
    musclesPrimary: ['triceps'],
    musclesSecondary: [],
    loadType: 'barbell',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Rope Triceps Pushdown',
    musclesPrimary: ['triceps'],
    musclesSecondary: ['forearms'],
    loadType: 'cable',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Bar Triceps Pushdown',
    musclesPrimary: ['triceps'],
    musclesSecondary: ['forearms'],
    loadType: 'cable',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Overhead Triceps Extension',
    musclesPrimary: ['triceps'],
    musclesSecondary: ['front_delts'],
    loadType: 'cable',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Single-Arm Dumbbell Katana Extension',
    musclesPrimary: ['triceps'],
    musclesSecondary: ['front_delts'],
    loadType: 'dumbbell',
    trackingType: 'reps',
    bilateral: false,
  },
  {
    name: 'Single-Arm Cable Katana Extension',
    musclesPrimary: ['triceps'],
    musclesSecondary: ['front_delts'],
    loadType: 'cable',
    trackingType: 'reps',
    bilateral: false,
  },
  {
    name: 'Bilateral Cable Katana Extension',
    musclesPrimary: ['triceps'],
    musclesSecondary: ['front_delts'],
    loadType: 'cable',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Bench Dips',
    musclesPrimary: ['triceps'],
    musclesSecondary: ['chest', 'front_delts'],
    loadType: 'bodyweight',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'JM Press',
    musclesPrimary: ['triceps'],
    musclesSecondary: ['chest', 'front_delts'],
    loadType: 'barbell',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Cable Triceps Kickback (Bilateral)',
    musclesPrimary: ['triceps'],
    musclesSecondary: ['rear_delts'],
    loadType: 'cable',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Single-Arm Dumbbell Triceps Kickback',
    musclesPrimary: ['triceps'],
    musclesSecondary: ['rear_delts'],
    loadType: 'dumbbell',
    trackingType: 'reps',
    bilateral: false,
  },

  // ── Legs — Quads ──────────────────────────────────────────────────────
  {
    name: 'Leg Extension (Machine)',
    musclesPrimary: ['quads'],
    musclesSecondary: [],
    loadType: 'machine',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Walking Lunges',
    musclesPrimary: ['quads', 'glutes'],
    musclesSecondary: ['hamstrings'],
    loadType: 'dumbbell',
    trackingType: 'reps',
    bilateral: false,
  },
  {
    name: '45 Degree Leg Press',
    musclesPrimary: ['quads'],
    musclesSecondary: ['glutes', 'hamstrings'],
    loadType: 'machine',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Horizontal Leg Press',
    musclesPrimary: ['quads'],
    musclesSecondary: ['glutes', 'hamstrings'],
    loadType: 'machine',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Barbell Back Squat',
    musclesPrimary: ['quads'],
    musclesSecondary: ['glutes', 'hamstrings', 'lower_back', 'abs'],
    loadType: 'barbell',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Smith Machine Squat',
    musclesPrimary: ['quads'],
    musclesSecondary: ['glutes', 'hamstrings'],
    loadType: 'machine',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Dumbbell Bulgarian Split Squat',
    musclesPrimary: ['quads'],
    musclesSecondary: ['glutes', 'hamstrings'],
    loadType: 'dumbbell',
    trackingType: 'reps',
    bilateral: false,
  },
  {
    name: 'Pendulum Squat',
    musclesPrimary: ['quads'],
    musclesSecondary: ['glutes', 'hamstrings'],
    loadType: 'machine',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Hack Squat',
    musclesPrimary: ['quads'],
    musclesSecondary: ['glutes', 'hamstrings'],
    loadType: 'machine',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Sissy Squat',
    musclesPrimary: ['quads'],
    musclesSecondary: ['abs'],
    loadType: 'bodyweight',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Static Lunges',
    musclesPrimary: ['quads'],
    musclesSecondary: ['glutes', 'hamstrings'],
    loadType: 'bodyweight',
    trackingType: 'reps',
    bilateral: false,
  },

  // ── Legs — Hamstrings  ────────────────────────────────────────
  {
    name: 'Barbell Good Morning',
    musclesPrimary: ['hamstrings'],
    musclesSecondary: ['glutes', 'lower_back'],
    loadType: 'barbell',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Seated Leg Curl',
    musclesPrimary: ['hamstrings'],
    musclesSecondary: ['calves'],
    loadType: 'machine',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Lying Leg Curl',
    musclesPrimary: ['hamstrings'],
    musclesSecondary: ['calves'],
    loadType: 'machine',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Stiff-Leg Deadlift',
    musclesPrimary: ['hamstrings'],
    musclesSecondary: ['glutes', 'lower_back'],
    loadType: 'barbell',
    trackingType: 'reps',
    bilateral: true,
  },

  // ── Legs — Glutes  ────────────────────────────────────────
  {
    name: 'Romanian Deadlift',
    musclesPrimary: ['glutes', 'hamstrings'],
    musclesSecondary: ['lower_back'],
    loadType: 'barbell',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Hip Thrust (Barbell)',
    musclesPrimary: ['glutes', 'hamstrings'],
    musclesSecondary: [],
    loadType: 'barbell',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Bulgarian Split Squat',
    musclesPrimary: ['glutes', 'quads'],
    musclesSecondary: ['hamstrings'],
    loadType: 'dumbbell',
    trackingType: 'reps',
    bilateral: false,
  },
  {
    name: 'Machine Hip Thrust',
    musclesPrimary: ['glutes'],
    musclesSecondary: ['hamstrings', 'quads'],
    loadType: 'machine',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Back Extensions',
    musclesPrimary: ['glutes'],
    musclesSecondary: ['hamstrings', 'lower_back'],
    loadType: 'bodyweight',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Machine Donkey Kick',
    musclesPrimary: ['glutes'],
    musclesSecondary: ['hamstrings'],
    loadType: 'machine',
    trackingType: 'reps',
    bilateral: false,
  },
  {
    name: 'Machine Glute Kickback',
    musclesPrimary: ['glutes'],
    musclesSecondary: ['hamstrings'],
    loadType: 'machine',
    trackingType: 'reps',
    bilateral: false,
  },
  {
    name: 'Cable Glute Kickback with Band',
    musclesPrimary: ['glutes'],
    musclesSecondary: ['hamstrings'],
    loadType: 'resistance_band',
    trackingType: 'reps',
    bilateral: false,
  },
  {
    name: 'Conventional Deadlift',
    musclesPrimary: ['glutes'],
    musclesSecondary: ['hamstrings', 'lower_back', 'traps'],
    loadType: 'barbell',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Dumbbell Romanian Deadlift',
    musclesPrimary: ['glutes'],
    musclesSecondary: ['hamstrings', 'lower_back'],
    loadType: 'dumbbell',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Machine Hip Abduction',
    musclesPrimary: ['abductors'],
    musclesSecondary: [],
    loadType: 'machine',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Machine Hip Adduction',
    musclesPrimary: ['adductors'],
    musclesSecondary: [],
    loadType: 'machine',
    trackingType: 'reps',
    bilateral: true,
  },

  // ── Calves (1) ────────────────────────────────────────────────────────────
  {
    name: 'Standing Calf Raise (Machine)',
    musclesPrimary: ['calves'],
    musclesSecondary: [],
    loadType: 'machine',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Single-Leg Dumbbell Calf Raise',
    musclesPrimary: ['calves'],
    musclesSecondary: ['forearms'],
    loadType: 'dumbbell',
    trackingType: 'reps',
    bilateral: false,
  },
  {
    name: 'Smith Machine Calf Raise',
    musclesPrimary: ['calves'],
    musclesSecondary: ['quads'],
    loadType: 'machine',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Hack Machine Calf Raise',
    musclesPrimary: ['calves'],
    musclesSecondary: ['quads'],
    loadType: 'machine',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: '45 Degree Leg Press Calf Raise',
    musclesPrimary: ['calves'],
    musclesSecondary: ['quads'],
    loadType: 'machine',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Seated Calf Raise Machine',
    musclesPrimary: ['calves'],
    musclesSecondary: [],
    loadType: 'machine',
    trackingType: 'reps',
    bilateral: true,
  },

  // ── Core (4) ──────────────────────────────────────────────────────────────
  {
    name: 'Plank',
    musclesPrimary: ['abs', 'lower_back'],
    musclesSecondary: [],
    loadType: 'bodyweight',
    trackingType: 'duration', // timed hold — no reps
    bilateral: true,
  },
  {
    name: 'Hanging Leg Raise',
    musclesPrimary: ['abs'],
    musclesSecondary: ['obliques'],
    loadType: 'bodyweight',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Cable Crunch',
    musclesPrimary: ['abs'],
    musclesSecondary: [],
    loadType: 'cable',
    trackingType: 'reps',
    bilateral: true,
  },
  {
    name: 'Ab Wheel Rollout',
    musclesPrimary: ['abs', 'lower_back'],
    musclesSecondary: [],
    loadType: 'bodyweight',
    trackingType: 'reps',
    bilateral: true,
  },
];

async function main(): Promise<void> {
  const mongoUri = process.env.MONGODB_URI;
  if (!mongoUri) {
    throw new Error('MONGODB_URI is not defined in environment variables');
  }

  await mongoose.connect(mongoUri);

  const ExerciseModel = mongoose.model(Exercise.name, ExerciseSchema);

  const existingCount = await ExerciseModel.countDocuments().exec();
  if (existingCount > 0) {
    console.log(
      `Skipping seed: ${existingCount} exercises already exist in the catalog`,
    );
    await mongoose.disconnect();
    return;
  }

  const result = await ExerciseModel.insertMany(EXERCISES);
  console.log(`Inserted ${result.length} exercises into the catalog`);

  await mongoose.disconnect();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
